#!/usr/bin/env bash
# init-direnv.sh — bootstrap direnv for a project
# Detects project type, writes an appropriate .envrc, runs `direnv allow`,
# and prints a quick verification (active Python & venv paths).
#
# Usage:
#   init-direnv [--manager poetry|uv|pip|pipenv|rye|conda] [--force|-f] [--dry-run|-n] [--inherit] [--standalone]
#
# Policy (nested dirs):
# - If this directory has project signals (pyproject.toml, requirements.txt, Pipfile, environment.yml, etc.),
#   we treat it as a **standalone** env and write a manager-specific .envrc.
# - Else, if this directory has a local `.env`, we write an `.envrc` that **inherits** the parent env via `source_up`
#   and then loads the local `.env` **after** inheritance so local vars override parent ones.
# - Else, with --inherit we explicitly inherit the parent.
# - Otherwise we auto-detect a manager (default Poetry if present; else pip) and write that.
#
set -euo pipefail

MANAGER="${MANAGER:-}"
FORCE=0
DRYRUN=0
INHERIT=0
STANDALONE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manager) MANAGER="${2:-}"; shift 2 ;;
    -f|--force) FORCE=1; shift ;;
    -n|--dry-run) DRYRUN=1; shift ;;
    --inherit) INHERIT=1; shift ;;
    --standalone) STANDALONE=1; shift ;;
    -h|--help)
      sed -n '1,120p' "$0"
      echo ""
      echo "Examples:"
      echo "  init-direnv                       # auto-detect; prefers local project signals"
      echo "  init-direnv --manager poetry      # force poetry here"
      echo "  init-direnv --inherit             # inherit parent .envrc in this subfolder"
      echo "  init-direnv --standalone          # force standalone env here even without signals"
      echo "  init-direnv --manager uv -f       # overwrite existing .envrc with uv template"
      exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1 ;;
  esac
done

exists() { command -v "$1" >/dev/null 2>&1; }

has_parent_envrc() {
  local d="$PWD"
  while [[ "$d" != "/" ]]; do
    d="$(dirname "$d")"
    if [[ -f "$d/.envrc" ]]; then
      echo "$d/.envrc"
      return 0
    fi
  done
  return 1
}

local_manager_signal() {
  # Poetry (pyproject with [tool.poetry] or poetry.lock)
  if [[ -f pyproject.toml ]]; then
    if grep -Eq '^\s*\[tool\.poetry\]' pyproject.toml || [[ -f poetry.lock ]]; then
      echo poetry; return
    fi
    # uv (explicit)
    if [[ -f uv.lock ]] || grep -Eq '^\s*\[tool\.uv\]' pyproject.toml; then
      echo uv; return
    fi
    # Rye
    if [[ -f rye.toml ]]; then
      echo rye; return
    fi
  fi
  # Pipenv
  if [[ -f Pipfile ]]; then
    echo pipenv; return
  fi
  # Conda
  if [[ -f environment.yml || -f .conda-env ]]; then
    echo conda; return
  fi
  # requirements.txt -> pip+venv
  if [[ -f requirements.txt ]]; then
    echo pip; return
  fi
  return 1
}

detect_manager() {
  # explicit override
  if [[ -n "${MANAGER:-}" ]]; then
    echo "$MANAGER"; return
  fi

  # Prefer CLI proof for Poetry if initialized
  if exists poetry; then
    if poetry env info -p >/dev/null 2>&1; then
      echo poetry; return
    fi
  fi

  # Local project signals
  if mgr="$(local_manager_signal)"; then
    echo "$mgr"; return
  fi

  # Last resort defaults
  if exists poetry; then
    echo poetry; return
  fi
  echo pip
}

write_inherit_envrc() {
  if [[ -f .envrc && $FORCE -ne 1 ]]; then
    echo ".envrc already exists. Use --force to overwrite, or remove it to inherit." >&2
    exit 1
  fi
  cat > .envrc <<'EOF'
# .envrc — inherit from parent, then load local .env if present (local overrides)
source_up
dotenv_if_exists
EOF
}

write_env_only_envrc() {
  if [[ -f .envrc && $FORCE -ne 1 ]]; then
    echo ".envrc already exists. Use --force to overwrite." >&2
    exit 1
  fi
  cat > .envrc <<'EOF'
# .envrc — local .env with parent inheritance
# Inherit parent env, then load local .env so it overrides parent values.
source_up
dotenv_if_exists
EOF
}

write_envrc() {
  local mgr="$1"

  if [[ -f .envrc && $FORCE -ne 1 ]]; then
    echo ".envrc already exists. Use --force to overwrite." >&2
    exit 1
  fi

  case "$mgr" in
    poetry)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (Poetry)
watch_file pyproject.toml
watch_file poetry.lock
dotenv_if_exists
source ~/.config/direnv/lib/poetry.sh
layout_poetry
EOF
      ;;
    uv)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (uv)
watch_file pyproject.toml
dotenv_if_exists
if [ ! -d .venv ]; then
  uv venv
fi
. .venv/bin/activate
EOF
      ;;
    pip)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (pip + stdlib venv)
watch_file requirements.txt
dotenv_if_exists
if [ ! -d .venv ]; then
  python3 -m venv .venv
fi
. .venv/bin/activate
EOF
      ;;
    pipenv)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (Pipenv)
dotenv_if_exists
PIPENV_VENV="$(pipenv --venv 2>/dev/null || true)"
if [ -n "$PIPENV_VENV" ] && [ -f "$PIPENV_VENV/bin/activate" ]; then
  . "$PIPENV_VENV/bin/activate"
else
  echo "No Pipenv venv found. Run 'pipenv install' once." >&2
fi
EOF
      ;;
    rye)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (Rye)
watch_file pyproject.toml
dotenv_if_exists
if [ ! -d .venv ]; then
  rye sync
fi
. .venv/bin/activate
EOF
      ;;
    conda)
      cat > .envrc <<'EOF'
# .envrc — generated by init-direnv.sh (Conda/Miniconda)
dotenv_if_exists
if command -v conda >/dev/null 2>&1; then
  # shellcheck disable=SC1091
  . "$(conda info --base)"/etc/profile.d/conda.sh
  ENV_NAME="${CONDA_ENV_NAME:-$(basename "$PWD")}"
  conda activate "$ENV_NAME" || echo "Create env first: conda create -n $ENV_NAME python=3.11"
else
  echo "conda not found on PATH." >&2
fi
EOF
      ;;
    *)
      echo "Unsupported manager: $mgr" >&2
      exit 1
      ;;
  esac
}

verify() {
  local mgr="$1"
  echo "== Verification =="
  case "$mgr" in
    poetry)
      (poetry env info -p || true)
      python -c 'import sys; print(sys.executable)'
      echo "${VIRTUAL_ENV:-}"
      ;;
    uv|pip|rye)
      test -d .venv && echo ".venv present"
      python -c 'import sys; print(sys.executable)'
      echo "${VIRTUAL_ENV:-}"
      ;;
    pipenv)
      PIPENV_VENV="$(pipenv --venv 2>/dev/null || true)"
      echo "PIPENV_VENV=${PIPENV_VENV:-<none>}"
      python -c 'import sys; print(sys.executable)'
      echo "${VIRTUAL_ENV:-}"
      ;;
    conda)
      echo "CONDA_DEFAULT_ENV=${CONDA_DEFAULT_ENV:-<none>}"
      python -c 'import sys; print(sys.executable)'
      ;;
    inherit|env-only)
      python -c 'import sys; print(sys.executable)'
      echo "${VIRTUAL_ENV:-}"
      ;;
  esac
}

main() {
  # If asked to inherit explicitly
  if [[ $INHERIT -eq 1 ]]; then
    if parent=$(has_parent_envrc); then
      echo "Inheriting parent .envrc at: $parent"
      write_inherit_envrc
      if command -v direnv >/dev/null 2>&1; then
        direnv allow || true
      fi
      verify inherit
      echo "Done."
      exit 0
    else
      echo "No parent .envrc found to inherit." >&2
      exit 2
    fi
  fi

  # If standalone was forced, ignore parent and write a manager-based envrc
  if [[ $STANDALONE -eq 1 ]]; then
    mgr="$(detect_manager)"
    echo "Standalone manager: $mgr"
    write_envrc "$mgr"
    if command -v direnv >/dev/null 2>&1; then
      direnv allow || true
    fi
    verify "$mgr"
    echo "Done."
    exit 0
  fi

  # If this directory has local project signals, treat as standalone
  if mgr="$(local_manager_signal)"; then
    echo "Detected local project manager: $mgr"
    write_envrc "$mgr"
    if command -v direnv >/dev/null 2>&1; then
      direnv allow || true
    fi
    verify "$mgr"
    echo "Done."
    exit 0
  fi

  # If there's a local .env, use it and inherit parent (local overrides)
  if [[ -f .env ]]; then
    echo "Found local .env; inheriting parent and loading local overrides."
    write_env_only_envrc
    if command -v direnv >/dev/null 2>&1; then
      direnv allow || true
    fi
    verify env-only
    echo "Done."
    exit 0
  fi

  # Otherwise, auto-detect a manager for a standalone env (favor Poetry if present)
  mgr="$(detect_manager)"
  echo "Detected manager: $mgr"
  write_envrc "$mgr"
  if command -v direnv >/dev/null 2>&1; then
    direnv allow || true
  fi
  verify "$mgr"
  echo "Done. Re-enter the directory or run: direnv reload"
}

main "$@"
